// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXfaHGPHolkuRGcWTG1KV3JJjI4xFB-Ro',
    appId: '1:436175933506:web:74e2d03bdc923069799ddb',
    messagingSenderId: '436175933506',
    projectId: 'rememberme-acm',
    authDomain: 'rememberme-acm.firebaseapp.com',
    storageBucket: 'rememberme-acm.appspot.com',
    measurementId: 'G-F5JMEE9K5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFnBN1W8hlQBOD7bWWbzQkfkQIj4qF7E',
    appId: '1:436175933506:android:b3ae9d87e6b61d05799ddb',
    messagingSenderId: '436175933506',
    projectId: 'rememberme-acm',
    storageBucket: 'rememberme-acm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpWqNzaW4hFWB42szIOQtWrxPQEHFqTrk',
    appId: '1:436175933506:ios:02cabf907b1bceed799ddb',
    messagingSenderId: '436175933506',
    projectId: 'rememberme-acm',
    storageBucket: 'rememberme-acm.appspot.com',
    iosClientId: '436175933506-jf7se592env1e46m0goe440u4q339ttj.apps.googleusercontent.com',
    iosBundleId: 'co.acmutd.rememberme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpWqNzaW4hFWB42szIOQtWrxPQEHFqTrk',
    appId: '1:436175933506:ios:02cabf907b1bceed799ddb',
    messagingSenderId: '436175933506',
    projectId: 'rememberme-acm',
    storageBucket: 'rememberme-acm.appspot.com',
    iosClientId: '436175933506-jf7se592env1e46m0goe440u4q339ttj.apps.googleusercontent.com',
    iosBundleId: 'co.acmutd.rememberme',
  );
}
